name: unet-from-scratch
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11

  # Core ML/DL packages (Apple Silicon optimized)
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0

  # Scientific computing (Apple Silicon optimized)
  - numpy>=1.24.0
  - scipy>=1.11.0

  # Data manipulation and visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - pillow>=10.0.0

  # Progress bars and utilities
  - tqdm>=4.65.0
  - requests>=2.31.0

  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.25.0
  - ipywidgets>=8.0.0

  # Development tools
  - black>=23.0.0
  - flake8>=6.0.0
  - pytest>=7.4.0
  - ruff>=0.1.0  # Fast Python linter

  # ML utilities (Apple Silicon compatible)
  - scikit-learn>=1.3.0
  - scikit-image>=0.21.0
  - opencv>=4.8.0

  # Additional useful packages
  - psutil  # System monitoring
  - h5py>=3.9.0  # HDF5 support
  - jsonschema>=4.19.0

  # Packages only available via pip
  - pip
  - pip:
    - tensorboard>=2.14.0
    - albumentations>=1.3.0
    - timm>=0.9.0  # PyTorch Image Models
    - torchmetrics>=1.2.0
    - lightning>=2.1.0  # PyTorch Lightning
    - hydra-core>=1.3.0  # Configuration management
    - rich>=13.0.0  # Beautiful terminal output
    - accelerate>=0.24.0  # Hugging Face acceleration library
    - transformers>=4.35.0  # For potential vision transformers
    - segmentation-models-pytorch>=0.3.3  # Pre-trained segmentation models
